# Jekyll site settings

title: PuppyByte
description: Paw-some apps dev

url: "https://puppybyte.dev"

# App Store Links
xpenses_app_store_url: "https://apps.apple.com/pt/app/xpenses-finances-tracker/id6743875432?l=en-GB"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

